"""Exact finite companions for Stage 1 FFF structures."""

from fts_lab.fff.admissibility import (
    admissible_count,
    count_admissible_by_enumeration,
    is_admissible,
    iter_admissible_functions,
)
from fts_lab.fff.cyclic_groups import (
    count_admissible_cyclic_homomorphisms_by_enumeration,
    count_cyclic_homomorphisms_by_enumeration,
    cyclic_homomorphism_count_formula,
    is_cyclic_homomorphism,
    source_cyclic_ratio,
)
from fts_lab.fff.functions import FunctionTuple, count_all_functions, iter_functions
from fts_lab.fff.measurable_spaces import (
    all_functions_measurable_by_special_case,
    count_admissible_measurable_functions_by_enumeration,
    count_measurable_functions_by_enumeration,
    event_algebra,
    inverse_image,
    is_measurable,
    measurable_bound_applies_to_partitions,
    partition_characteristic,
    partition_order,
    source_measurable_bound_ratio,
    source_measurable_upper_bound,
    validate_partition,
)
from fts_lab.fff.permutation_groups import (
    compose_permutations,
    conjugate_permutation,
    identity_permutation,
    inverse_permutation,
    is_second_order_homomorphism,
    is_second_order_respectful,
    source_permutation_ratio,
    source_permutation_respectful_count,
    validate_permutation,
)
from fts_lab.fff.total_orders import (
    count_total_order_witnesses_by_enumeration,
    count_unique_total_order_homomorphisms_by_enumeration,
    is_order_preserving,
    is_order_reversing,
    orientation_witnesses,
    source_total_order_ratio,
    source_total_order_witness_count,
    unique_total_order_homomorphism_count,
    unique_total_order_ratio,
)

__all__ = [
    "FunctionTuple",
    "admissible_count",
    "all_functions_measurable_by_special_case",
    "compose_permutations",
    "conjugate_permutation",
    "count_admissible_by_enumeration",
    "count_admissible_cyclic_homomorphisms_by_enumeration",
    "count_admissible_measurable_functions_by_enumeration",
    "count_all_functions",
    "count_cyclic_homomorphisms_by_enumeration",
    "count_measurable_functions_by_enumeration",
    "count_total_order_witnesses_by_enumeration",
    "count_unique_total_order_homomorphisms_by_enumeration",
    "cyclic_homomorphism_count_formula",
    "event_algebra",
    "identity_permutation",
    "inverse_image",
    "inverse_permutation",
    "is_admissible",
    "is_cyclic_homomorphism",
    "is_measurable",
    "is_order_preserving",
    "is_order_reversing",
    "is_second_order_homomorphism",
    "is_second_order_respectful",
    "iter_admissible_functions",
    "iter_functions",
    "measurable_bound_applies_to_partitions",
    "orientation_witnesses",
    "partition_characteristic",
    "partition_order",
    "source_cyclic_ratio",
    "source_measurable_bound_ratio",
    "source_measurable_upper_bound",
    "source_permutation_ratio",
    "source_permutation_respectful_count",
    "source_total_order_ratio",
    "source_total_order_witness_count",
    "unique_total_order_homomorphism_count",
    "unique_total_order_ratio",
    "validate_partition",
    "validate_permutation",
]
