"""Finite measurable-space helpers for FFF Stage 3.

These utilities implement the source-explicit finite partition checks from the Stage 3
draft spec. They keep exact counts separate from the source upper bound and do not
resolve the pending independent-review questions in ``ASM-FFF-0003``.
"""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from fractions import Fraction
from itertools import chain, combinations

from fts_lab.fff.admissibility import admissible_count, is_admissible
from fts_lab.fff.functions import (
    FunctionTuple,
    iter_functions,
    require_positive_size,
    require_positive_sizes,
    validate_function,
)

type Block = tuple[int, ...]
type Event = tuple[int, ...]
type Partition = tuple[Block, ...]


def validate_partition(
    partition: Sequence[Sequence[int]],
    carrier_size: int | None = None,
) -> Partition:
    """Validate and canonicalize a finite partition of ``0..carrier_size-1``."""
    if carrier_size is not None:
        require_positive_size("carrier_size", carrier_size)

    raw_blocks = tuple(tuple(block) for block in partition)
    if not raw_blocks:
        raise ValueError("partition must contain at least one block")

    seen: set[int] = set()
    blocks: list[Block] = []
    for block in raw_blocks:
        if not block:
            raise ValueError("partition blocks must be non-empty")
        if any(element < 0 for element in block):
            raise ValueError("partition labels must be non-negative")
        block_set = set(block)
        if len(block_set) != len(block):
            raise ValueError(f"partition block contains duplicate labels: {block}")
        overlap = seen & block_set
        if overlap:
            raise ValueError(f"partition blocks must be disjoint, overlap={sorted(overlap)}")
        seen.update(block_set)
        blocks.append(tuple(sorted(block_set)))

    if carrier_size is None:
        carrier_size = max(seen) + 1

    expected = set(range(carrier_size))
    if seen != expected:
        raise ValueError(f"partition must cover exactly 0..{carrier_size - 1}, got {sorted(seen)}")

    return tuple(sorted(blocks, key=lambda block: (block[0], block)))


def partition_carrier_size(partition: Sequence[Sequence[int]]) -> int:
    """Return the size of the finite set partitioned by ``partition``."""
    return sum(len(block) for block in validate_partition(partition))


def partition_order(partition: Sequence[Sequence[int]]) -> int:
    """Return the source order ``k``: the number of base blocks."""
    return len(validate_partition(partition))


def partition_characteristic(partition: Sequence[Sequence[int]]) -> tuple[int, ...]:
    """Return the partition characteristic as a sorted multiset of block sizes."""
    return tuple(sorted(len(block) for block in validate_partition(partition)))


def is_discrete_partition(partition: Sequence[Sequence[int]]) -> bool:
    """Return true when every base block is a singleton."""
    return all(len(block) == 1 for block in validate_partition(partition))


def is_trivial_partition(partition: Sequence[Sequence[int]]) -> bool:
    """Return true when the algebra has only one base block."""
    return len(validate_partition(partition)) == 1


def event_algebra(partition: Sequence[Sequence[int]]) -> tuple[Event, ...]:
    """Return all events generated by a finite partition basis."""
    blocks = validate_partition(partition)
    events: list[Event] = []
    for selected_count in range(len(blocks) + 1):
        for indexes in combinations(range(len(blocks)), selected_count):
            event = tuple(sorted(chain.from_iterable(blocks[index] for index in indexes)))
            events.append(event)
    return tuple(sorted(events, key=lambda event: (len(event), event)))


def is_union_of_blocks(
    candidate: Sequence[int],
    partition: Sequence[Sequence[int]],
) -> bool:
    """Return true when ``candidate`` is a union of base blocks from ``partition``."""
    blocks = validate_partition(partition)
    carrier_size = sum(len(block) for block in blocks)
    candidate_set = _validate_event(candidate, carrier_size=carrier_size, name="candidate")

    reconstructed: set[int] = set()
    for block in blocks:
        block_set = set(block)
        if block_set <= candidate_set:
            reconstructed.update(block_set)
        elif block_set & candidate_set:
            return False
    return reconstructed == candidate_set


def inverse_image(
    function: Sequence[int],
    codomain_event: Sequence[int],
    *,
    codomain_size: int | None = None,
) -> Event:
    """Return the inverse image of a finite codomain event under ``function``."""
    if codomain_size is None:
        merged_values = tuple(function) + tuple(codomain_event)
        if not merged_values:
            raise ValueError("cannot infer codomain_size from empty function and event")
        codomain_size = max(merged_values) + 1

    values = validate_function(function, codomain_size)
    event = _validate_event(codomain_event, carrier_size=codomain_size, name="codomain_event")
    return tuple(index for index, value in enumerate(values) if value in event)


def is_measurable(
    function: Sequence[int],
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> bool:
    """Check finite partition measurability by inverse images of codomain blocks."""
    w_blocks = validate_partition(w_partition)
    v_blocks = validate_partition(v_partition)
    domain_size = sum(len(block) for block in w_blocks)
    codomain_size = sum(len(block) for block in v_blocks)
    values = validate_function(function, codomain_size, domain_size=domain_size)

    for v_block in v_blocks:
        preimage = inverse_image(values, v_block, codomain_size=codomain_size)
        if not is_union_of_blocks(preimage, w_blocks):
            return False
    return True


def iter_measurable_functions(
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> Iterator[FunctionTuple]:
    """Yield all measurable functions for small finite partitioned spaces."""
    w_blocks = validate_partition(w_partition)
    v_blocks = validate_partition(v_partition)
    domain_size = sum(len(block) for block in w_blocks)
    codomain_size = sum(len(block) for block in v_blocks)
    for function in iter_functions(domain_size, codomain_size):
        if is_measurable(function, w_blocks, v_blocks):
            yield function


def count_measurable_functions_by_enumeration(
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> int:
    """Return the exact small finite measurable-function count by enumeration."""
    return sum(1 for _ in iter_measurable_functions(w_partition, v_partition))


def count_admissible_measurable_functions_by_enumeration(
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> int:
    """Return the exact small measurable-function count after admissibility filtering."""
    codomain_size = partition_carrier_size(v_partition)
    return sum(
        1
        for function in iter_measurable_functions(w_partition, v_partition)
        if is_admissible(function, codomain_size)
    )


def all_functions_measurable_by_special_case(
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> bool:
    """Return true for the source special cases where every function is measurable."""
    return is_discrete_partition(w_partition) or is_trivial_partition(v_partition)


def source_measurable_upper_bound(
    domain_size: int,
    codomain_size: int,
    domain_order: int,
) -> int:
    """Return the Appendix A.5 integer upper bound for numeric theorem parameters.

    This helper validates only ``n``, ``m``, and ``k``. Use
    ``measurable_bound_applies_to_partitions`` when concrete partition bases are
    available, because trivial/discrete special cases are partition-level properties.
    """
    require_measurable_bound_scope(domain_size, codomain_size, domain_order)
    return int(
        codomain_size ** (domain_order - 1)
        + (codomain_size ** (domain_order - 1))
        * ((codomain_size - 1) ** (domain_size - domain_order + 1))
    )


def source_measurable_bound_ratio(
    domain_size: int,
    codomain_size: int,
    domain_order: int,
) -> Fraction:
    """Return the source upper bound over the admissible payoff-function denominator."""
    return Fraction(
        source_measurable_upper_bound(domain_size, codomain_size, domain_order),
        admissible_count(domain_size, codomain_size),
    )


def measurable_bound_applies_to_partitions(
    w_partition: Sequence[Sequence[int]],
    v_partition: Sequence[Sequence[int]],
) -> bool:
    """Return true when partitions satisfy the nontrivial/nondiscrete theorem scope."""
    w_blocks = validate_partition(w_partition)
    v_blocks = validate_partition(v_partition)
    domain_size = sum(len(block) for block in w_blocks)
    domain_order = len(w_blocks)
    codomain_size = sum(len(block) for block in v_blocks)
    return (
        codomain_size >= 2
        and 2 <= domain_order <= domain_size - 1
        and not is_trivial_partition(w_blocks)
        and not is_discrete_partition(w_blocks)
        and not is_trivial_partition(v_blocks)
    )


def require_measurable_bound_scope(
    domain_size: int,
    codomain_size: int,
    domain_order: int,
) -> None:
    """Reject inputs outside the source bound's stated finite theorem scope."""
    require_positive_sizes(domain_size, codomain_size)
    require_positive_size("domain_order", domain_order)
    if codomain_size < 2:
        raise ValueError(f"codomain_size must be at least 2, got {codomain_size}")
    if domain_order < 2 or domain_order > domain_size - 1:
        raise ValueError(
            "domain_order must satisfy 2 <= k <= n - 1 for the source bound, "
            f"got n={domain_size}, k={domain_order}"
        )


def _validate_event(candidate: Sequence[int], *, carrier_size: int, name: str) -> set[int]:
    values = tuple(candidate)
    value_set = set(values)
    if len(value_set) != len(values):
        raise ValueError(f"{name} contains duplicate labels: {values}")
    if any(value < 0 or value >= carrier_size for value in values):
        raise ValueError(f"{name} labels must be in 0..{carrier_size - 1}, got {values}")
    return value_set
