"""Exact FBT numerical reproduction helpers."""

from fts_lab.fbt.atlas_oracle import (
    MAP_TIE_DISTINCT_TRUTH_FITNESS,
    MAP_TIE_NONE,
    MAP_TIE_SAME_TRUTH_FITNESS,
    OBSERVATION_EVALUATED,
    STATUS_BLOCKED_ZERO_MARGINAL,
    STATUS_DIFFERENT_BEST_EQUAL_EXPECTED_FITNESS,
    STATUS_FITNESS_ONLY_DECISION_TIE,
    STATUS_FITNESS_ONLY_STRICTLY_DOMINATES_TRUTH,
    STATUS_MAP_TIE_POLICY_SENSITIVE,
    STATUS_SAME_BEST_OBSERVATION,
    STATUS_TRUTH_DECISION_TIE,
    ZERO_MARGINAL_UNDEFINED,
    CellOracleResult,
    ObservationOracleResult,
    evaluate_observation,
    evaluate_primary_cell,
    map_estimates,
)
from fts_lab.fbt.bayes import (
    AmbiguousMapEstimateError,
    FiniteBayesianDecisionProblem,
    WorldStateRow,
    ZeroMarginalProbabilityError,
    observation_marginal,
    posterior,
    unique_map_estimate,
)
from fts_lab.fbt.decision import (
    AmbiguousFitnessDecisionError,
    expected_fitness,
    unique_best_observation,
)

__all__ = [
    "MAP_TIE_DISTINCT_TRUTH_FITNESS",
    "MAP_TIE_NONE",
    "MAP_TIE_SAME_TRUTH_FITNESS",
    "OBSERVATION_EVALUATED",
    "STATUS_BLOCKED_ZERO_MARGINAL",
    "STATUS_DIFFERENT_BEST_EQUAL_EXPECTED_FITNESS",
    "STATUS_FITNESS_ONLY_DECISION_TIE",
    "STATUS_FITNESS_ONLY_STRICTLY_DOMINATES_TRUTH",
    "STATUS_MAP_TIE_POLICY_SENSITIVE",
    "STATUS_SAME_BEST_OBSERVATION",
    "STATUS_TRUTH_DECISION_TIE",
    "ZERO_MARGINAL_UNDEFINED",
    "AmbiguousFitnessDecisionError",
    "AmbiguousMapEstimateError",
    "CellOracleResult",
    "FiniteBayesianDecisionProblem",
    "ObservationOracleResult",
    "WorldStateRow",
    "ZeroMarginalProbabilityError",
    "evaluate_observation",
    "evaluate_primary_cell",
    "expected_fitness",
    "map_estimates",
    "observation_marginal",
    "posterior",
    "unique_best_observation",
    "unique_map_estimate",
]
